"""initial_schema

Revision ID: 22d651e39295
Revises: 
Create Date: 2026-07-02 19:46:43.402228

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22d651e39295'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('auc_roc', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('dataset_size', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions'))
    )
    op.create_index(op.f('ix_model_versions_model_type'), 'model_versions', ['model_type'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_logs'))
    )
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_service'), 'system_logs', ['service'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('old_value_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('upi_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('upi_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('receiver_name', sa.String(length=255), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('patterns_flagged_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('scan_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_upi_scans_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upi_scans'))
    )
    op.create_index(op.f('ix_upi_scans_created_at'), 'upi_scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_upi_scans_upi_id'), 'upi_scans', ['upi_id'], unique=False)
    op.create_index(op.f('ix_upi_scans_user_id'), 'upi_scans', ['user_id'], unique=False)
    op.create_index(op.f('ix_upi_scans_verdict'), 'upi_scans', ['verdict'], unique=False)
    op.create_table('url_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('url_raw', sa.Text(), nullable=False),
    sa.Column('url_normalized', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('features_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('scan_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_url_scans_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_url_scans'))
    )
    op.create_index(op.f('ix_url_scans_created_at'), 'url_scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_url_scans_url_normalized'), 'url_scans', ['url_normalized'], unique=False)
    op.create_index(op.f('ix_url_scans_user_id'), 'url_scans', ['user_id'], unique=False)
    op.create_index(op.f('ix_url_scans_verdict'), 'url_scans', ['verdict'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_type', sa.String(length=10), nullable=False),
    sa.Column('url_scan_id', sa.UUID(), nullable=True),
    sa.Column('upi_scan_id', sa.UUID(), nullable=True),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('shap_values_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('top_features_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_predictions_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upi_scan_id'], ['upi_scans.id'], name=op.f('fk_predictions_upi_scan_id_upi_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['url_scan_id'], ['url_scans.id'], name=op.f('fk_predictions_url_scan_id_url_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index(op.f('ix_predictions_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_predictions_scan_type'), 'predictions', ['scan_type'], unique=False)
    op.create_index(op.f('ix_predictions_upi_scan_id'), 'predictions', ['upi_scan_id'], unique=False)
    op.create_index(op.f('ix_predictions_url_scan_id'), 'predictions', ['url_scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_url_scan_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_upi_scan_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_scan_type'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_version_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_url_scans_verdict'), table_name='url_scans')
    op.drop_index(op.f('ix_url_scans_user_id'), table_name='url_scans')
    op.drop_index(op.f('ix_url_scans_url_normalized'), table_name='url_scans')
    op.drop_index(op.f('ix_url_scans_created_at'), table_name='url_scans')
    op.drop_table('url_scans')
    op.drop_index(op.f('ix_upi_scans_verdict'), table_name='upi_scans')
    op.drop_index(op.f('ix_upi_scans_user_id'), table_name='upi_scans')
    op.drop_index(op.f('ix_upi_scans_upi_id'), table_name='upi_scans')
    op.drop_index(op.f('ix_upi_scans_created_at'), table_name='upi_scans')
    op.drop_table('upi_scans')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_logs_service'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_model_versions_model_type'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
